---
# role: ansible-role-packer-provision
# file: tasks/swap.yml

- name: "Disable all swap files"
  command: "swapoff -a"
  changed_when: False
  when: ansible_swaptotal_mb > 0

- name: "Delete swap file"
  file:
    path: "/swapfile"
    state: absent

- name: "Remove swap entry from fstab"
  mount:
    path: "{{ item.mount }}"
    state: absent
  loop: "{{ ansible_mounts }}"
  when: item.fstype == "swap"

- name: "Set swappiness to zero"
  lineinfile:
    path: "/etc/sysctl.d/99-swappiness.conf"
    regexp: "^vm.swappiness"
    line: "vm.swappiness=0"
    owner: root
    group: root
    mode: 0644
    create: yes
    state: present
