---
# role: ansible-role-packer-provision
# file: tasks/swap.yml

- name: "Disable all swap files"
  ansible.builtin.command: "swapoff -a"
  changed_when: false
  when: ansible_swaptotal_mb > 0

- name: "Delete swap file"
  ansible.builtin.file:
    path: "/swapfile"
    state: absent

- name: "Remove swap entry from fstab"
  ansible.posix.mount:
    path: "{{ item.mount }}"
    state: absent
  loop: "{{ ansible_mounts }}"
  when: item.fstype == "swap"

- name: "Set swappiness to zero"
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '0'
    reload: true
    state: present
    sysctl_set: true
    sysctl_file: "/etc/sysctl.d/99-swappiness.conf"
