---
# role: ansible-role-packer-provision
# file: tasks/swap.yml

- name: "Disable all swap files"
  shell: "swapoff -a"
  tags: ['skip_ansible_lint']

- name: "Delete swap file"
  file:
    path: "/swapfile"
    state: absent

- name: "Remove swap entry from fstab"
  lineinfile:
    path: "/etc/fstab"
    regexp: "^.*swapfile.*$"
    state: absent

- name: "Set swappiness to zero"
  lineinfile:
    path: "/etc/sysctl.d/99-swappiness.conf"
    regexp: "^vm.swappiness"
    line: "vm.swappiness=0"
    owner: root
    group: root
    mode: 0644
    create: yes
    state: present
