---
# role: ansible-role-packer-provision
# file: tasks/vagrant.yml

- name: "Add {{ ansible_ssh_user }} sudoers.d file"
  lineinfile:
    path: "/etc/sudoers.d/{{ ansible_ssh_user }}"
    regexp: '^{{ ansible_ssh_user }}'
    line: "{{ ansible_ssh_user }}  ALL=(ALL)   NOPASSWD:ALL"
    owner: root
    group: root
    mode: 0440
    create: yes
    state: present
    validate: /usr/sbin/visudo -cf %s

- name: "Create {{ ansible_ssh_user }} .ssh directory"
  file:
    path: "/home/{{ ansible_ssh_user }}/.ssh"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0700

- name: "Add vagrant public key"
  authorized_key:
    user: "{{ ansible_ssh_user }}"
    key: https://github.com/mitchellh/vagrant/raw/master/keys/vagrant.pub
    state: present
    exclusive: no
  when: ansible_ssh_user == "vagrant"

- name: "Add {{ ansible_ssh_user }} public key"
  authorized_key:
    user: "{{ ansible_ssh_user }}"
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
    state: present
    exclusive: no
  when: ansible_ssh_user != "vagrant"
