---
# role: ansible-role-packer-provision
# file: tasks/vagrant.yml

- name: "Add vagrant sudoers.d file"
  lineinfile:
    path: /etc/sudoers.d/vagrant
    regexp: '^vagrant'
    line: "vagrant  ALL=(ALL)   NOPASSWD:ALL"
    owner: root
    group: root
    mode: 0440
    create: yes
    state: present
    validate: /usr/sbin/visudo -cf %s

- name: "Create vagrant .ssh directory"
  file:
    path: /home/vagrant/.ssh
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0700

- name: "Get vagrant public key"
  get_url:
    url: https://github.com/mitchellh/vagrant/raw/master/keys/vagrant.pub
    dest: /home/vagrant/.ssh/authorized_keys
    owner: vagrant
    group: vagrant
    mode: 0600
