---
# role: ansible-role-packer-provision
# file: tasks/virtualbox.yml

- name: "Get VirtualBox version"
  shell: "cat /home/{{ ansible_user }}/.vbox_version"
  register: virtualbox_version
  tags: ['skip_ansible_lint']

- name: "Ensure mount directory is present"
  file:
    path: /mnt/vbox
    state: directory
    mode: 0755

- name: "Mount VirtualBox guest additions ISO"
  mount:
    name: "/mnt/vbox"
    src: "/home/{{ ansible_user }}/VBoxGuestAdditions_{{ virtualbox_version.stdout }}.iso"
    opts: loop
    state: mounted
    fstype: iso9660

- name: "Run VirtualBox guest additions installation"
  shell: sh /mnt/vbox/VBoxLinuxAdditions.run
  creates: /usr/bin/VBoxClient
  tags: ['skip_ansible_lint']

- name: "Unmount VirtualBox guest additions ISO"
  mount:
    name: "/mnt/vbox"
    state: absent

- name: "Delete VirtualBox guest additions ISO and mount point"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/home/{{ ansible_user }}/VBoxGuestAdditions_{{ virtualbox_version.stdout }}.iso"
    - "/mnt/vbox"
