---
# role: ansible-role-pp
# file: molecule/vbox/molecule.yml

dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
    type: virtualbox
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: pp-alpine310
    box: "generic/alpine310"
    cpus: 2
    memory: 1024
  - name: pp-arch
    box: "archlinux/archlinux"
    cpus: 2
    memory: 1024
  - name: pp-centos8
    box: "centos/8"
    cpus: 2
    memory: 1024
  - name: pp-debian10
    box: "debian/buster64"
    cpus: 2
    memory: 1024
  - name: pp-fedora31
    box: "fedora/31-cloud-base"
    cpus: 2
    memory: 1024
  - name: pp-ubuntu1804
    box: "ubuntu/bionic64"
    cpus: 2
    memory: 1024
  - name: pp-ubuntu2004
    box: "ubuntu/focal64"
    cpus: 2
    memory: 1024
provisioner:
  name: ansible
  log: True
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
  inventory:
    group_vars:
      all:
        packer_builder_type: "virtualbox-iso"
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore"
  directory: ../resources/tests
  options:
    v: True
    sudo: True
