---
# role: ansible-role-packer-provision
# file: molecule/vbox/molecule.yml

dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
    type: virtualbox
lint:
  name: yamllint
  options:
    config-file: molecule/shared/yamllint.yml
platforms:
  # - name: packer-arch
  #   box: "archlinux/archlinux"
  #   cpus: 2
  #   memory: 1024
  # - name: packer-centos8
  #   box: "centos/8"
  #   cpus: 2
  #   memory: 1024
  # - name: packer-debian10
  #   box: "debian/buster64"
  #   cpus: 2
  #   memory: 1024
  # - name: packer-suse
  #   box: "bento/opensuse-leap-15.1"
  #   cpus: 2
  #   memory: 1024
  - name: packer-ubuntu1804
    box: "ubuntu/bionic64"
    cpus: 2
    memory: 1024
provisioner:
  name: ansible
  log: True
  lint:
    name: ansible-lint
  playbooks:
    prepare: prepare.yml
    converge: ../shared/playbook.yml
    # inventory:
    #   group_vars:
    #     all:
    #       packer_provision_enabled: True
scenario:
  name: default
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore"
  directory: ../tests
  options:
    v: True
    sudo: True
  lint:
    name: flake8
