---
# role: ansible-role-packer-provision
# file: molecule/resources/playbooks/converge.yml

- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: "Include variables to converge playbook"
      ansible.builtin.include_vars: vars.yml
  roles:
    # if you want to enable requirements put them in requirements.yml
    # and add here
    # - role: common
    - role: ansible-role-packer-provision
